### PR TITLE
Fix the 2 opened issues

### PR DESCRIPTION
**Pull request by ultrasuperpingu**
Fix default economy temp value
Add delta max temperature as a parameter

Accidentally (it was supposed to be in another branch) added custom pages to visualize thermostats data (to copy in www/template)

### CODE REVIEW

**Review by 999LV — CHANGES_REQUESTED** [review]
@ultrasuperpingu, many thanks for all your work on this web interface... Most appreciated I still need to test your pull requests, but I do not like the fixed IP for the server at "192.168.0.1" since many systems (like mines) are on a different IP subnetwork (and possibly same issue with the 8080 port). In my view, these parameters (i.e. Parameters["Address"] and Parameters["Port"] in the plugin.py code) need to be passed somehow to the server. Not sure how to best do it though.

**Comment by ultrasuperpingu** [comment]
Those parameters was supposed to be edited before copying the files (Smart Thermostats.html and svt_viewer.js) in the www/templates directory. The domoticz example of custom pages (custom.example) is using a hard coded url too... I changed and just use the same address/port than the current page.

**Comment by 999LV** [comment]
@ultrasuperpingu , many thanks for the change. May I make one more request to automate the installation ? possibly move the html and js files to a ./templates/ subfolder of the plugin folder and copy/remove these files to the ./www/templates/ folder in the onStart and onStop methods as per suggestion in [https://www.domoticz.com/wiki/Developing_a_Python_plugin#Setup_custom_page_within_plugin](url)
Not that I want to be a pain (your work is a great addition), but this makes the whole thing more transparent to the user.
Cheers.

**Comment by ultrasuperpingu** [comment]
Ok, I'll look at that this evening.

**Comment by ultrasuperpingu** [comment]
Ok, I added file copying on plugin startup. I didn't delete files on pluggin stop since you can have multiple (and usually do) multiple instances on the plugin and you don't want the viewer to be deleted when you stop an instance...
I'm really not sure this feature is a good idea though. If one do not want to have this custom page, it can not be suppressed as the custom page id copied at plugin startup. Manual install is to me a better option.

**Comment by 999LV** [comment]
@ultrasuperpingu , thanks for this and your comments. I’ll test and think through it, hopefully over the weekend (I am super busy these days with my day job). The plugin is very popular and we do not want to introduce breaking changes but your work also makes me thinking about more user friendly set up options (I am not familiar with js so never focused on it).

**Comment by ultrasuperpingu** [comment]
The viewer is independant from the plugin code. There is no breaking changes either if you use the startup install or choose to let the users to manually install the custom page (maybe just write a simple bash script to copy the files is enough?).

That being said, I'm using the plugin for 2 weeks now and I'd like to propose some propositions for improvement and some will probably be breaking changes. But I think it's not a huge problem as long as there is a documentation to tell users how to migrate to a new version. They'd have the choice to do the migration or to stick with the old version...

And all that being said, thanks again for the plugin. I really think it should be integrated to domoticz as core :)

**Comment by 999LV** [comment]
@ultrasuperpingu , I agree with you about no automatic install (my bad for causing extra work). I adjusted your PR accordingly and made a few cosmetic updates. Accepting you pull request with many thanks. Ideally the plugin page in the domoticz wiki needs to be updated as well.
This gave me some ideas about a "setup" custom page to replace the cluttered plugin parameters page and all its CSV data entry, but this is a lot of work (and I need to catch up with js and angularjs ...). May be for the next lock-down.

**Comment by ultrasuperpingu** [comment]
@999LV No problem for extra work, I can handle this little work :). For plugin configuration, I opened an issue with some proposition including an other way to to it...

**Comment by jakenl** [comment]
My first response to the GUI for SVT was 'Wow'. Many times, when I try to understand how SVT managed to do a good job, or that it needs a little tweaking,  I am switching back and forth between the switch page, temperature page and setpoint page. This puts it all nicely together!

A big point of improvement can be made in the scaling. With current low temperatures outside, the setpoint and inside temperatures are more or less a flat line on the top and the outside temperature on the bottom of the graph. I can't learn anything from that. Both inside, outside and setpoint should have their own vertical scale. While multiply y-axes can be difficicult to interpret in normal life, it is no problem for understanding and checking the behaviour of SVT

**Comment by ultrasuperpingu** [comment]
I agree that when all curves are displayed, then graph can be hard to interpret, but outside, inside and setpoint using the same scaling does provide an information. I'm not sure it is a good idea to remove it. You can click on the curve legend to show/hide it (and then, the scaling change to fit the displayed curves) so there is no need IMHO to display outside temperature with a different scale.

**Pull request merged**
